# .github/workflows/test.yml

name: Run Python tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  uv-example:
    name: Run tests with uv
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest tests/test_preprocess.py
